### ISSUE TITLE
Invalid `content` property throwing errors

### ISSUE THREAD

**Issue by christianbundy** [ssbc/secure-scuttlebutt#217]
I think I've caused/found a failure mode by setting the property `"content": "&sbBmsB(...).sha256"` as mentioned [in this thread](https://github.com/flumedb/flumelog-offset/issues/13#issuecomment-422475518).  I'm currently unclear on the severity of this bug, or whether my experiment is causing problems for others on the network. I'm getting two errors on master:

```
Error: public_key must be a buffer of size crypto_scalarmult_BYTES
    at exports.crypto_scalarmult (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/sodium-chloride/index.js:118:8)
    at Object.exports.decrypt.exports.multibox_open (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/private-box/index.js:60:16)
    at exports.unbox (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-keys/index.js:157:16)
    at Array.main_unboxer (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:60:49)
    at unbox (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:21:36)
    at Object.decode (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:68:14)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/flumelog-offset/inject.js:45:22
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:74:11
    at get (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:29:7)
```

```
Error: bad p size
    at Object.nacl.scalarMult (/home/christianbundy/Source/patchwork/node_modules/tweetnacl/nacl-fast.js:2202:51)
    at exports.crypto_scalarmult (/home/christianbundy/Source/patchwork/node_modules/sodium-browserify-tweetnacl/index.js:76:31)
    at Object.exports.decrypt.exports.multibox_open (/home/christianbundy/Source/patchwork/node_modules/private-box/index.js:60:16)
    at exports.unbox (/home/christianbundy/Source/patchwork/node_modules/ssb-keys/index.js:157:16)
    at Array.main_unboxer (/home/christianbundy/Source/patchwork/node_modules/secure-scuttlebutt/minimal.js:60:49)
    at unbox (/home/christianbundy/Source/patchwork/node_modules/secure-scuttlebutt/minimal.js:21:36)
    at Object.decode (/home/christianbundy/Source/patchwork/node_modules/secure-scuttlebutt/minimal.js:68:14)
    at /home/christianbundy/Source/patchwork/node_modules/flumelog-offset/inject.js:76:29
    at /home/christianbundy/Source/patchwork/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/christianbundy/Source/patchwork/node_modules/aligned-block-file/blocks.js:74:11
```

I think we may be able to resolve this bug by wrapping [`ssbKeys.unbox()`](https://github.com/ssbc/ssb-keys/blob/2d9c2dd96b5c94e3d73bad41884fc6a31be7e4bc/index.js#L153-L162) in a `try...catch` block, or wrapping it [here](https://github.com/ssbc/secure-scuttlebutt/blob/beff8d063a20a1604ffe9110eb0d0f0911fc2e95/minimal.js#L21) so that unbox errors can be handled without anything catching fire.

**Comment by christianbundy** [comment]
Looks like this likely is *not* breaking SSB for others, it's instead just crashing other instances of sbot on my network as they're trying to decrypt the non-encrypted string. The result is that my message isn't being replicated, although I believe it *is* still a valid message. I think my options are:

- Reset my feed and lose my most recent ~30 posts.
- Wait until a bugfix is merged and remain unreplicated until others upgrade their client(s).

:thinking: 

Maybe there's some way to cherry-pick that post and delete it from my feed?

**Comment by dominictarr** [comment]
guessing you already rewound? I got this

```
$ sbot createHistoryStream --id @+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519 --limit 1 --sequence 4884
{
  "key": "%P9zniL4UHLj9eCPGA59vZi70NNgl8r6wx9SBujiuyIY=.sha256",
  "value": {
    "previous": "%mfW9YauWJFrfmyglCVzQ2NN+q7i2bd6iNiXCpgfxmqo=.sha256",
    "sequence": 4884,
    "author": "@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519",
    "timestamp": 1537316752645,
    "hash": "sha256",
    "content": {
      "type": "chess_move",
      "ply": 19,
      "root": "%Hc6wouM2eztGqBg37QXFXgYqXlMSWLBGdg4pSN4o3xw=.sha256",
      "orig": "d1",
      "dest": "e2",
      "pgnMove": "Ke2",
      "fen": "2kr1b1r/ppp2ppp/2n5/3Bpb2/4n3/2N1BN2/PPP1KPPP/R6R b - - 7 10",
      "branch": "%bfx7kmHkz2jMZi8Ch+Fw7lpxNsm4Z/8tYlcZrIkb3k8=.sha256"
    },
    "signature": "JZnhixVRMo4ubTuDWxo5Q8vYFux7/h4WpfoywdoMxt7oGPw/QRvOogQJ0Li1AHlhwBwyjJubCxdvrAyTABbDAA==.sig.ed25519"
  },
  "timestamp": 1537327814787
}
```

**Comment by christianbundy** [comment]
Yeah, I took the output from `createHistoryStream` and added all of my posts *without* the funky one. Maybe this is a Scuttlebot problem instead? Here's how I can reproduce locally:

1. Create a completely new feed (`@Q0SqHwaRFKV3LgDdxqkKBluG8oIjZdFzN2fN6z0vFVs=.ed25519`)
2. Join a pub.
3. Patch secure-scuttlebutt and ssb-validate.
4. Run `sbot publish '&blob'`

Here's the diff for ssb-validate (patched 3.0.9):

```diff
diff --git a/index.js b/index.js
index b0bcd21..61e4448 100644
--- a/index.js
+++ b/index.js
@@ -37,8 +37,12 @@ function isEncrypted (str) {
   return isString(str) && /^[0-9A-Za-z\/+]+={0,2}\.box/.test(str)
 }
 
+function isBlob( str) {
+  return isString(str) && str.indexOf('&') === 0;
+}
+
 var isInvalidContent = exports.isInvalidContent = function (content) {
-  if(!isEncrypted(content)) {
+  if(!isEncrypted(content) && !isBlob(content)) {
     var type = content.type
     if (!(isString(type) && type.length <= 52 && type.length >= 3)) {
       return new Error('type must be a string' +
@@ -54,7 +58,7 @@ var isInvalidShape = exports.isInvalidShape = function (msg) {
     !isObject(msg) ||
     !isInteger(msg.sequence) ||
     !isFeedId(msg.author) ||
-    !(isObject(msg.content) || isEncrypted(msg.content))
+    !(isObject(msg.content) || isEncrypted(msg.content) || isBlob(msg.content))
   )
     return new Error('message has invalid properties:'+JSON.stringify(msg, null, 2))
 
@@ -196,7 +200,7 @@ exports.validate = function (state, hmac_key, feed) {
 exports.create = function (state, keys, hmac_key, content, timestamp) {
   if(timestamp == null || isNaN(+timestamp)) throw new Error('timestamp must be provided')
   state = flatState(state)
-  if(!isObject(content) && !isEncrypted(content))
+  if(!isObject(content) && !isEncrypted(content) && !isBlob(content))
     throw new Error('invalid message content, must be object or encrypted string')
```

When I run `createHistoryStream` locally it shows the entire feed correctly, including the &blob message. When I look from the perspective of another instance (like my pub) it doesn't show the last message. I've followed the test profile from my main account, so you *should* be able to see it (although the &blob content doesn't replicate).

<details>
<summary>Feed (click to expand)</summary>

```json
{
  "key": "%AbujaxR69c0h9oKGUambEbXkkDs6x66W/08iqV73aBI=.sha256",
  "value": {
    "previous": null,
    "author": "@Q0SqHwaRFKV3LgDdxqkKBluG8oIjZdFzN2fN6z0vFVs=.ed25519",
    "sequence": 1,
    "timestamp": 1537373031139,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@gTsBPQbdSd763h0qoZsBjPlgWbhKKmMFW8kmTv/XrV8=.ed25519",
      "following": true
    },
    "signature": "qeSLV927tyTg7JXjB8yQ9IXV5vsRSKpHa3HinHosa6fcwNv0k6yludSb19Mm7qUPeAV5Uj8cahS5aNVUtoGKBQ==.sig.ed25519"
  },
  "timestamp": 1537373031206
}

{
  "key": "%WL6EqEwMk4TqCLKfKS5BMBDobi47ML/JVGAAm+NlnoQ=.sha256",
  "value": {
    "previous": "%AbujaxR69c0h9oKGUambEbXkkDs6x66W/08iqV73aBI=.sha256",
    "author": "@Q0SqHwaRFKV3LgDdxqkKBluG8oIjZdFzN2fN6z0vFVs=.ed25519",
    "sequence": 2,
    "timestamp": 1537373174697,
    "hash": "sha256",
    "content": {
      "type": "pub",
      "address": {
        "host": "libra.fraction.io",
        "port": 8008,
        "key": "@gTsBPQbdSd763h0qoZsBjPlgWbhKKmMFW8kmTv/XrV8=.ed25519"
      }
    },
    "signature": "MaoRuUm5oI97RJYUMf1hWR9udVLH62nSX4BwOq7d0WNfGl93xqaXYExMH5EYkjZ5SJuMhRTqJ+2hltxnwdFtAQ==.sig.ed25519"
  },
  "timestamp": 1537373174762
}

{
  "key": "%DPlK9GIdIPEaSIKzzlNqtsBQ2JgAf0wcwwzCW2oYD8w=.sha256",
  "value": {
    "previous": "%WL6EqEwMk4TqCLKfKS5BMBDobi47ML/JVGAAm+NlnoQ=.sha256",
    "author": "@Q0SqHwaRFKV3LgDdxqkKBluG8oIjZdFzN2fN6z0vFVs=.ed25519",
    "sequence": 3,
    "timestamp": 1537373174939,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@gTsBPQbdSd763h0qoZsBjPlgWbhKKmMFW8kmTv/XrV8=.ed25519",
      "following": true,
      "autofollow": true
    },
    "signature": "B67cSFitlbQoB65fC8o/lNe2wHf3hzUpE94Xa4Ce2ihGWorSx1te2hSLYv5EGuJ238J0wcsdFEDv4XRbqmn9Bw==.sig.ed25519"
  },
  "timestamp": 1537373174995
}

{
  "key": "%OKqk7WKQggxGqwbGk+BbbCdpcH3p3MV1rDPE+gvJE8g=.sha256",
  "value": {
    "previous": "%DPlK9GIdIPEaSIKzzlNqtsBQ2JgAf0wcwwzCW2oYD8w=.sha256",
    "sequence": 4,
    "author": "@Q0SqHwaRFKV3LgDdxqkKBluG8oIjZdFzN2fN6z0vFVs=.ed25519",
    "timestamp": 1537373332656,
    "hash": "sha256",
    "content": "&sbBmsB7XWvmIzkBzreYcuzPpLtpeCMDIs6n/OJGSC1U=.sha256",
    "signature": "8kdZKsM9T9bt86B47gOmgOp+Xzx1TRC8rw09ih22a91w6tR8c+2Dkwo0V/xfMIucL2K3ZvQliwJJuEva8h9TCw==.sig.ed25519"
  },
  "timestamp": 1537373332677
}
```
</details>

**Comment by christianbundy** [comment]
Oh, I think your test just clicked for me -- is your point that ssb-validate is saying "that's an invalid message" and refusing to replicate? I was under the impression that `content` could be any arbitrary value so long as it conformed to JSON, but if that's not the case then it makes sense why it isn't being replicated.

**Comment by dominictarr** [comment]
@christianbundy yeah, I would have thought that your scuttlebot would refuse to even store that message - but it does seem that others receiving it did. Probably the reason it was accepted is that there might be some legacy stuff about messages you create locally?

**Comment by dominictarr** [comment]
rejecting invalid messages would be a good test case for http://github.com/ssbc/ssb-integration-tests

**Comment by christianbundy** [comment]
Also closing in favor of https://github.com/ssbc/ssb-keys/pull/46.
